/* This file was automatically generated by CasADi 3.6.6.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) car_PDM_expl_vde_forw_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

static const casadi_int casadi_s0[11] = {7, 1, 0, 7, 0, 1, 2, 3, 4, 5, 6};
static const casadi_int casadi_s1[59] = {7, 7, 0, 7, 14, 21, 28, 35, 42, 49, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6};
static const casadi_int casadi_s2[5] = {1, 1, 0, 1, 0};
static const casadi_int casadi_s3[3] = {0, 0, 0};

/* car_PDM_expl_vde_forw:(i0[7],i1[7x7],i2[7],i3,i4[])->(o0[7],o1[7x7],o2[7]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a2, a20, a21, a22, a23, a24, a25, a26, a27, a3, a4, a5, a6, a7, a8, a9;
  a0=arg[0]? arg[0][3] : 0;
  a1=arg[0]? arg[0][5] : 0;
  a2=(a0*a1);
  if (res[0]!=0) res[0][0]=a2;
  a2=arg[0]? arg[0][0] : 0;
  a3=arg[0]? arg[0][4] : 0;
  a4=cos(a3);
  a5=(a2*a4);
  a3=sin(a3);
  a6=(a0*a3);
  a5=(a5-a6);
  if (res[0]!=0) res[0][1]=a5;
  a5=(a2*a3);
  a6=(a0*a4);
  a5=(a5+a6);
  if (res[0]!=0) res[0][2]=a5;
  a5=101060.;
  a6=1380.;
  a7=(a6*a2);
  a8=(a5/a7);
  a9=(a8-a2);
  a10=(a9*a1);
  a11=310000.;
  a11=(a11/a7);
  a12=(a11*a0);
  a10=(a10-a12);
  a12=120000.;
  a13=arg[0]? arg[0][6] : 0;
  a14=(a12*a13);
  a14=(a14/a6);
  a10=(a10+a14);
  if (res[0]!=0) res[0][3]=a10;
  if (res[0]!=0) res[0][4]=a1;
  a10=2.6345000000000000e+03;
  a14=(a10*a2);
  a5=(a5/a14);
  a15=(a5*a0);
  a16=6.0545356000000006e+05;
  a16=(a16/a14);
  a17=(a16*a1);
  a15=(a15-a17);
  a17=166080.;
  a13=(a17*a13);
  a13=(a13/a10);
  a15=(a15+a13);
  if (res[0]!=0) res[0][5]=a15;
  a15=arg[3]? arg[3][0] : 0;
  if (res[0]!=0) res[0][6]=a15;
  a15=arg[1]? arg[1][3] : 0;
  a13=(a1*a15);
  a18=arg[1]? arg[1][5] : 0;
  a19=(a0*a18);
  a13=(a13+a19);
  if (res[1]!=0) res[1][0]=a13;
  a13=arg[1]? arg[1][0] : 0;
  a19=(a4*a13);
  a20=arg[1]? arg[1][4] : 0;
  a21=(a3*a20);
  a22=(a2*a21);
  a19=(a19-a22);
  a22=(a3*a15);
  a20=(a4*a20);
  a23=(a0*a20);
  a22=(a22+a23);
  a19=(a19-a22);
  if (res[1]!=0) res[1][1]=a19;
  a19=(a3*a13);
  a20=(a2*a20);
  a19=(a19+a20);
  a20=(a4*a15);
  a21=(a0*a21);
  a20=(a20-a21);
  a19=(a19+a20);
  if (res[1]!=0) res[1][2]=a19;
  a19=(a9*a18);
  a8=(a8/a7);
  a20=(a6*a13);
  a21=(a8*a20);
  a21=(a21+a13);
  a21=(a1*a21);
  a19=(a19-a21);
  a21=(a11*a15);
  a7=(a11/a7);
  a20=(a7*a20);
  a20=(a0*a20);
  a21=(a21-a20);
  a19=(a19-a21);
  a21=7.2463768115942030e-04;
  a20=arg[1]? arg[1][6] : 0;
  a22=(a12*a20);
  a22=(a21*a22);
  a19=(a19+a22);
  if (res[1]!=0) res[1][3]=a19;
  if (res[1]!=0) res[1][4]=a18;
  a15=(a5*a15);
  a19=(a5/a14);
  a13=(a10*a13);
  a22=(a19*a13);
  a22=(a0*a22);
  a15=(a15-a22);
  a18=(a16*a18);
  a14=(a16/a14);
  a13=(a14*a13);
  a13=(a1*a13);
  a18=(a18-a13);
  a15=(a15-a18);
  a18=3.7957866767887642e-04;
  a20=(a17*a20);
  a20=(a18*a20);
  a15=(a15+a20);
  if (res[1]!=0) res[1][5]=a15;
  a15=0.;
  if (res[1]!=0) res[1][6]=a15;
  a20=arg[1]? arg[1][10] : 0;
  a13=(a1*a20);
  a22=arg[1]? arg[1][12] : 0;
  a23=(a0*a22);
  a13=(a13+a23);
  if (res[1]!=0) res[1][7]=a13;
  a13=arg[1]? arg[1][7] : 0;
  a23=(a4*a13);
  a24=arg[1]? arg[1][11] : 0;
  a25=(a3*a24);
  a26=(a2*a25);
  a23=(a23-a26);
  a26=(a3*a20);
  a24=(a4*a24);
  a27=(a0*a24);
  a26=(a26+a27);
  a23=(a23-a26);
  if (res[1]!=0) res[1][8]=a23;
  a23=(a3*a13);
  a24=(a2*a24);
  a23=(a23+a24);
  a24=(a4*a20);
  a25=(a0*a25);
  a24=(a24-a25);
  a23=(a23+a24);
  if (res[1]!=0) res[1][9]=a23;
  a23=(a9*a22);
  a24=(a6*a13);
  a25=(a8*a24);
  a25=(a25+a13);
  a25=(a1*a25);
  a23=(a23-a25);
  a25=(a11*a20);
  a24=(a7*a24);
  a24=(a0*a24);
  a25=(a25-a24);
  a23=(a23-a25);
  a25=arg[1]? arg[1][13] : 0;
  a24=(a12*a25);
  a24=(a21*a24);
  a23=(a23+a24);
  if (res[1]!=0) res[1][10]=a23;
  if (res[1]!=0) res[1][11]=a22;
  a20=(a5*a20);
  a13=(a10*a13);
  a23=(a19*a13);
  a23=(a0*a23);
  a20=(a20-a23);
  a22=(a16*a22);
  a13=(a14*a13);
  a13=(a1*a13);
  a22=(a22-a13);
  a20=(a20-a22);
  a25=(a17*a25);
  a25=(a18*a25);
  a20=(a20+a25);
  if (res[1]!=0) res[1][12]=a20;
  if (res[1]!=0) res[1][13]=a15;
  a20=arg[1]? arg[1][17] : 0;
  a25=(a1*a20);
  a22=arg[1]? arg[1][19] : 0;
  a13=(a0*a22);
  a25=(a25+a13);
  if (res[1]!=0) res[1][14]=a25;
  a25=arg[1]? arg[1][14] : 0;
  a13=(a4*a25);
  a23=arg[1]? arg[1][18] : 0;
  a24=(a3*a23);
  a26=(a2*a24);
  a13=(a13-a26);
  a26=(a3*a20);
  a23=(a4*a23);
  a27=(a0*a23);
  a26=(a26+a27);
  a13=(a13-a26);
  if (res[1]!=0) res[1][15]=a13;
  a13=(a3*a25);
  a23=(a2*a23);
  a13=(a13+a23);
  a23=(a4*a20);
  a24=(a0*a24);
  a23=(a23-a24);
  a13=(a13+a23);
  if (res[1]!=0) res[1][16]=a13;
  a13=(a9*a22);
  a23=(a6*a25);
  a24=(a8*a23);
  a24=(a24+a25);
  a24=(a1*a24);
  a13=(a13-a24);
  a24=(a11*a20);
  a23=(a7*a23);
  a23=(a0*a23);
  a24=(a24-a23);
  a13=(a13-a24);
  a24=arg[1]? arg[1][20] : 0;
  a23=(a12*a24);
  a23=(a21*a23);
  a13=(a13+a23);
  if (res[1]!=0) res[1][17]=a13;
  if (res[1]!=0) res[1][18]=a22;
  a20=(a5*a20);
  a25=(a10*a25);
  a13=(a19*a25);
  a13=(a0*a13);
  a20=(a20-a13);
  a22=(a16*a22);
  a25=(a14*a25);
  a25=(a1*a25);
  a22=(a22-a25);
  a20=(a20-a22);
  a24=(a17*a24);
  a24=(a18*a24);
  a20=(a20+a24);
  if (res[1]!=0) res[1][19]=a20;
  if (res[1]!=0) res[1][20]=a15;
  a20=arg[1]? arg[1][24] : 0;
  a24=(a1*a20);
  a22=arg[1]? arg[1][26] : 0;
  a25=(a0*a22);
  a24=(a24+a25);
  if (res[1]!=0) res[1][21]=a24;
  a24=arg[1]? arg[1][21] : 0;
  a25=(a4*a24);
  a13=arg[1]? arg[1][25] : 0;
  a23=(a3*a13);
  a26=(a2*a23);
  a25=(a25-a26);
  a26=(a3*a20);
  a13=(a4*a13);
  a27=(a0*a13);
  a26=(a26+a27);
  a25=(a25-a26);
  if (res[1]!=0) res[1][22]=a25;
  a25=(a3*a24);
  a13=(a2*a13);
  a25=(a25+a13);
  a13=(a4*a20);
  a23=(a0*a23);
  a13=(a13-a23);
  a25=(a25+a13);
  if (res[1]!=0) res[1][23]=a25;
  a25=(a9*a22);
  a13=(a6*a24);
  a23=(a8*a13);
  a23=(a23+a24);
  a23=(a1*a23);
  a25=(a25-a23);
  a23=(a11*a20);
  a13=(a7*a13);
  a13=(a0*a13);
  a23=(a23-a13);
  a25=(a25-a23);
  a23=arg[1]? arg[1][27] : 0;
  a13=(a12*a23);
  a13=(a21*a13);
  a25=(a25+a13);
  if (res[1]!=0) res[1][24]=a25;
  if (res[1]!=0) res[1][25]=a22;
  a20=(a5*a20);
  a24=(a10*a24);
  a25=(a19*a24);
  a25=(a0*a25);
  a20=(a20-a25);
  a22=(a16*a22);
  a24=(a14*a24);
  a24=(a1*a24);
  a22=(a22-a24);
  a20=(a20-a22);
  a23=(a17*a23);
  a23=(a18*a23);
  a20=(a20+a23);
  if (res[1]!=0) res[1][26]=a20;
  if (res[1]!=0) res[1][27]=a15;
  a20=arg[1]? arg[1][31] : 0;
  a23=(a1*a20);
  a22=arg[1]? arg[1][33] : 0;
  a24=(a0*a22);
  a23=(a23+a24);
  if (res[1]!=0) res[1][28]=a23;
  a23=arg[1]? arg[1][28] : 0;
  a24=(a4*a23);
  a25=arg[1]? arg[1][32] : 0;
  a13=(a3*a25);
  a26=(a2*a13);
  a24=(a24-a26);
  a26=(a3*a20);
  a25=(a4*a25);
  a27=(a0*a25);
  a26=(a26+a27);
  a24=(a24-a26);
  if (res[1]!=0) res[1][29]=a24;
  a24=(a3*a23);
  a25=(a2*a25);
  a24=(a24+a25);
  a25=(a4*a20);
  a13=(a0*a13);
  a25=(a25-a13);
  a24=(a24+a25);
  if (res[1]!=0) res[1][30]=a24;
  a24=(a9*a22);
  a25=(a6*a23);
  a13=(a8*a25);
  a13=(a13+a23);
  a13=(a1*a13);
  a24=(a24-a13);
  a13=(a11*a20);
  a25=(a7*a25);
  a25=(a0*a25);
  a13=(a13-a25);
  a24=(a24-a13);
  a13=arg[1]? arg[1][34] : 0;
  a25=(a12*a13);
  a25=(a21*a25);
  a24=(a24+a25);
  if (res[1]!=0) res[1][31]=a24;
  if (res[1]!=0) res[1][32]=a22;
  a20=(a5*a20);
  a23=(a10*a23);
  a24=(a19*a23);
  a24=(a0*a24);
  a20=(a20-a24);
  a22=(a16*a22);
  a23=(a14*a23);
  a23=(a1*a23);
  a22=(a22-a23);
  a20=(a20-a22);
  a13=(a17*a13);
  a13=(a18*a13);
  a20=(a20+a13);
  if (res[1]!=0) res[1][33]=a20;
  if (res[1]!=0) res[1][34]=a15;
  a20=arg[1]? arg[1][38] : 0;
  a13=(a1*a20);
  a22=arg[1]? arg[1][40] : 0;
  a23=(a0*a22);
  a13=(a13+a23);
  if (res[1]!=0) res[1][35]=a13;
  a13=arg[1]? arg[1][35] : 0;
  a23=(a4*a13);
  a24=arg[1]? arg[1][39] : 0;
  a25=(a3*a24);
  a26=(a2*a25);
  a23=(a23-a26);
  a26=(a3*a20);
  a24=(a4*a24);
  a27=(a0*a24);
  a26=(a26+a27);
  a23=(a23-a26);
  if (res[1]!=0) res[1][36]=a23;
  a23=(a3*a13);
  a24=(a2*a24);
  a23=(a23+a24);
  a24=(a4*a20);
  a25=(a0*a25);
  a24=(a24-a25);
  a23=(a23+a24);
  if (res[1]!=0) res[1][37]=a23;
  a23=(a9*a22);
  a24=(a6*a13);
  a25=(a8*a24);
  a25=(a25+a13);
  a25=(a1*a25);
  a23=(a23-a25);
  a25=(a11*a20);
  a24=(a7*a24);
  a24=(a0*a24);
  a25=(a25-a24);
  a23=(a23-a25);
  a25=arg[1]? arg[1][41] : 0;
  a24=(a12*a25);
  a24=(a21*a24);
  a23=(a23+a24);
  if (res[1]!=0) res[1][38]=a23;
  if (res[1]!=0) res[1][39]=a22;
  a20=(a5*a20);
  a13=(a10*a13);
  a23=(a19*a13);
  a23=(a0*a23);
  a20=(a20-a23);
  a22=(a16*a22);
  a13=(a14*a13);
  a13=(a1*a13);
  a22=(a22-a13);
  a20=(a20-a22);
  a25=(a17*a25);
  a25=(a18*a25);
  a20=(a20+a25);
  if (res[1]!=0) res[1][40]=a20;
  if (res[1]!=0) res[1][41]=a15;
  a20=arg[1]? arg[1][45] : 0;
  a25=(a1*a20);
  a22=arg[1]? arg[1][47] : 0;
  a13=(a0*a22);
  a25=(a25+a13);
  if (res[1]!=0) res[1][42]=a25;
  a25=arg[1]? arg[1][42] : 0;
  a13=(a4*a25);
  a23=arg[1]? arg[1][46] : 0;
  a24=(a3*a23);
  a26=(a2*a24);
  a13=(a13-a26);
  a26=(a3*a20);
  a23=(a4*a23);
  a27=(a0*a23);
  a26=(a26+a27);
  a13=(a13-a26);
  if (res[1]!=0) res[1][43]=a13;
  a13=(a3*a25);
  a23=(a2*a23);
  a13=(a13+a23);
  a23=(a4*a20);
  a24=(a0*a24);
  a23=(a23-a24);
  a13=(a13+a23);
  if (res[1]!=0) res[1][44]=a13;
  a13=(a9*a22);
  a23=(a6*a25);
  a24=(a8*a23);
  a24=(a24+a25);
  a24=(a1*a24);
  a13=(a13-a24);
  a24=(a11*a20);
  a23=(a7*a23);
  a23=(a0*a23);
  a24=(a24-a23);
  a13=(a13-a24);
  a24=arg[1]? arg[1][48] : 0;
  a23=(a12*a24);
  a23=(a21*a23);
  a13=(a13+a23);
  if (res[1]!=0) res[1][45]=a13;
  if (res[1]!=0) res[1][46]=a22;
  a20=(a5*a20);
  a25=(a10*a25);
  a13=(a19*a25);
  a13=(a0*a13);
  a20=(a20-a13);
  a22=(a16*a22);
  a25=(a14*a25);
  a25=(a1*a25);
  a22=(a22-a25);
  a20=(a20-a22);
  a24=(a17*a24);
  a24=(a18*a24);
  a20=(a20+a24);
  if (res[1]!=0) res[1][47]=a20;
  if (res[1]!=0) res[1][48]=a15;
  a15=arg[2]? arg[2][3] : 0;
  a20=(a1*a15);
  a24=arg[2]? arg[2][5] : 0;
  a22=(a0*a24);
  a20=(a20+a22);
  if (res[2]!=0) res[2][0]=a20;
  a20=arg[2]? arg[2][0] : 0;
  a22=(a4*a20);
  a25=arg[2]? arg[2][4] : 0;
  a13=(a3*a25);
  a23=(a2*a13);
  a22=(a22-a23);
  a23=(a3*a15);
  a25=(a4*a25);
  a26=(a0*a25);
  a23=(a23+a26);
  a22=(a22-a23);
  if (res[2]!=0) res[2][1]=a22;
  a3=(a3*a20);
  a2=(a2*a25);
  a3=(a3+a2);
  a4=(a4*a15);
  a13=(a0*a13);
  a4=(a4-a13);
  a3=(a3+a4);
  if (res[2]!=0) res[2][2]=a3;
  a9=(a9*a24);
  a6=(a6*a20);
  a8=(a8*a6);
  a8=(a8+a20);
  a8=(a1*a8);
  a9=(a9-a8);
  a11=(a11*a15);
  a7=(a7*a6);
  a7=(a0*a7);
  a11=(a11-a7);
  a9=(a9-a11);
  a11=arg[2]? arg[2][6] : 0;
  a12=(a12*a11);
  a21=(a21*a12);
  a9=(a9+a21);
  if (res[2]!=0) res[2][3]=a9;
  if (res[2]!=0) res[2][4]=a24;
  a5=(a5*a15);
  a10=(a10*a20);
  a19=(a19*a10);
  a0=(a0*a19);
  a5=(a5-a0);
  a16=(a16*a24);
  a14=(a14*a10);
  a1=(a1*a14);
  a16=(a16-a1);
  a5=(a5-a16);
  a17=(a17*a11);
  a18=(a18*a17);
  a5=(a5+a18);
  if (res[2]!=0) res[2][5]=a5;
  a5=1.;
  if (res[2]!=0) res[2][6]=a5;
  return 0;
}

CASADI_SYMBOL_EXPORT int car_PDM_expl_vde_forw(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int car_PDM_expl_vde_forw_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int car_PDM_expl_vde_forw_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void car_PDM_expl_vde_forw_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int car_PDM_expl_vde_forw_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void car_PDM_expl_vde_forw_release(int mem) {
}

CASADI_SYMBOL_EXPORT void car_PDM_expl_vde_forw_incref(void) {
}

CASADI_SYMBOL_EXPORT void car_PDM_expl_vde_forw_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int car_PDM_expl_vde_forw_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int car_PDM_expl_vde_forw_n_out(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_real car_PDM_expl_vde_forw_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* car_PDM_expl_vde_forw_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* car_PDM_expl_vde_forw_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* car_PDM_expl_vde_forw_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s0;
    case 3: return casadi_s2;
    case 4: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* car_PDM_expl_vde_forw_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int car_PDM_expl_vde_forw_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5;
  if (sz_res) *sz_res = 3;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int car_PDM_expl_vde_forw_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 3*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
